# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appstate/plugin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61ppstate/plugin.proto\x12\x08\x61ppstate\"\x12\n\x10\x41ppStateRelationB\"\n\x1e\x64\x65.grundprinzip.appstate.protoP\x01\x62\x06proto3')



_APPSTATERELATION = DESCRIPTOR.message_types_by_name['AppStateRelation']
AppStateRelation = _reflection.GeneratedProtocolMessageType('AppStateRelation', (_message.Message,), {
  'DESCRIPTOR' : _APPSTATERELATION,
  '__module__' : 'appstate.plugin_pb2'
  # @@protoc_insertion_point(class_scope:appstate.AppStateRelation)
  })
_sym_db.RegisterMessage(AppStateRelation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036de.grundprinzip.appstate.protoP\001'
  _APPSTATERELATION._serialized_start=35
  _APPSTATERELATION._serialized_end=53
# @@protoc_insertion_point(module_scope)
